COCO_NAMES = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

DEFAULT_VEHICLE_CLASSES = ("car", "bus", "truck")


def class_ids_from_names(names: list[str] | tuple[str, ...]) -> set[int]:
    return class_ids_from_model_names(names, COCO_NAMES)


def class_ids_from_model_names(
    names: list[str] | tuple[str, ...],
    model_names: list[str] | tuple[str, ...],
) -> set[int]:
    missing = [name for name in names if name not in model_names]
    if missing:
        valid = ", ".join(DEFAULT_VEHICLE_CLASSES)
        raise ValueError(f"Unknown model class name(s): {missing}. Example valid vehicle classes: {valid}")
    return {model_names.index(name) for name in names}
